import { describe, expect, it } from "vitest";
import {
  renderCallers,
  renderInitCaller,
  renderLoopCaller,
} from "../src/caller-templates.js";

const nonComment = (s: string) =>
  s.split("\n").filter((l) => l.trim() !== "" && !l.trim().startsWith("#")).length;

describe("renderInitCaller", () => {
  it("emits the exact cross-org init caller (fixture)", () => {
    expect(renderInitCaller()).toBe(
      [
        "# .github/workflows/looppilot-init.yml",
        "# Generated by `gh looppilot init`. Thin caller — implementation lives in",
        "# the reusable workflow team-yubune/loop-pilot/.github/workflows/init.yml@v1.",
        "name: LoopPilot Init",
        "",
        "on:",
        "  pull_request:",
        "    types: [opened, ready_for_review, labeled]",
        "",
        "jobs:",
        "  init:",
        "    permissions:",
        "      contents: read",
        "      pull-requests: write",
        "      issues: write",
        "    uses: team-yubune/loop-pilot/.github/workflows/init.yml@v1",
        "    secrets:",
        "      CODEX_REVIEW_REQUEST_TOKEN: ${{ secrets.CODEX_REVIEW_REQUEST_TOKEN }}",
        "",
      ].join("\n"),
    );
  });

  it("uses secrets: inherit for a same-repo caller", () => {
    const out = renderInitCaller({ sameRepo: true });
    expect(out).toContain("secrets: inherit");
    expect(out).not.toContain("CODEX_REVIEW_REQUEST_TOKEN:");
  });
});

describe("renderLoopCaller", () => {
  it("emits the exact cross-org loop caller for language=node (fixture)", () => {
    expect(renderLoopCaller({ language: "node" })).toBe(
      [
        "# .github/workflows/looppilot-loop.yml",
        "# Generated by `gh looppilot init`. Thin caller — implementation lives in",
        "# the reusable workflow team-yubune/loop-pilot/.github/workflows/loop.yml@v1.",
        "name: LoopPilot Loop",
        "",
        "on:",
        "  issue_comment:",
        "    types: [created]",
        "  pull_request_review:",
        "    types: [submitted]",
        "",
        "jobs:",
        "  loop:",
        "    permissions:",
        "      contents: write",
        "      pull-requests: write",
        "      issues: write",
        "      actions: read",
        "    uses: team-yubune/loop-pilot/.github/workflows/loop.yml@v1",
        "    secrets:",
        "      CODEX_REVIEW_REQUEST_TOKEN: ${{ secrets.CODEX_REVIEW_REQUEST_TOKEN }}",
        "      LOOPPILOT_PUSH_TOKEN: ${{ secrets.LOOPPILOT_PUSH_TOKEN }}",
        "      # Set exactly one of ANTHROPIC_API_KEY / CLAUDE_CODE_OAUTH_TOKEN.",
        "      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}",
        "      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}",
        "    with:",
        "      language: node",
        "",
      ].join("\n"),
    );
  });

  it("passes the detected language through to the `language:` input", () => {
    for (const lang of ["python", "go", "rust", "none"] as const) {
      expect(renderLoopCaller({ language: lang })).toContain(`language: ${lang}`);
    }
  });

  it("includes the full permission set incl. actions: read and all 4 secrets", () => {
    const out = renderLoopCaller();
    for (const p of ["contents: write", "pull-requests: write", "issues: write", "actions: read"]) {
      expect(out).toContain(p);
    }
    for (const s of [
      "CODEX_REVIEW_REQUEST_TOKEN",
      "LOOPPILOT_PUSH_TOKEN",
      "ANTHROPIC_API_KEY",
      "CLAUDE_CODE_OAUTH_TOKEN",
    ]) {
      expect(out).toContain(s);
    }
  });

  it("references the reusable workflow by @v1 (never a frozen full workflow)", () => {
    const out = renderLoopCaller();
    expect(out).toContain("uses: team-yubune/loop-pilot/.github/workflows/loop.yml@v1");
    // No gate logic / steps leaked into the caller.
    expect(out).not.toContain("chatgpt-codex-connector[bot]");
    expect(out).not.toContain("runs-on:");
    expect(out).not.toContain("steps:");
  });

  it("supports a pinned ref and a custom repo (for forks / mirrors)", () => {
    const out = renderLoopCaller({ ref: "v1.2.3", actionRepo: "acme/loop-pilot" });
    expect(out).toContain("uses: acme/loop-pilot/.github/workflows/loop.yml@v1.2.3");
  });
});

describe("renderCallers", () => {
  it("returns both callers with their .github/workflows/ paths", () => {
    const callers = renderCallers({ language: "go" });
    expect(callers.map((c) => c.path)).toEqual([
      ".github/workflows/looppilot-init.yml",
      ".github/workflows/looppilot-loop.yml",
    ]);
  });

  it("keeps both callers thin (init <= 22, loop <= 26 non-comment lines)", () => {
    const [init, loop] = renderCallers();
    expect(nonComment(init.content)).toBeLessThanOrEqual(22);
    expect(nonComment(loop.content)).toBeLessThanOrEqual(26);
  });
});
