/**
 * Thin caller-workflow generation for `gh looppilot init` (TY-346).
 *
 * Generates the ~15-22 line callers that reference the reusable workflows
 * (TY-345) by `@v1`. NEVER generates a full workflow — a frozen full workflow
 * would rot in each adopter repo and defeat central updates (ADR-0001 / TY-345).
 *
 * Built from plain string arrays (not template literals) so the literal
 * `${{ secrets.X }}` GitHub expressions pass through verbatim.
 */
import type { WorkflowLanguage } from "./toolchain.js";

export interface CallerOptions {
  /** Reusable-workflow language input for the loop caller. Default "node". */
  language?: WorkflowLanguage;
  /** Moving major ref to pin. Default "v1". */
  ref?: string;
  /** owner/repo hosting the reusable workflows. Default "team-yubune/loop-pilot". */
  actionRepo?: string;
  /**
   * Same-repo caller → `secrets: inherit`. Cross-org adopter (default) →
   * enumerate the four custom secrets (`secrets: inherit` is same-org only).
   */
  sameRepo?: boolean;
}

const DEFAULT_REPO = "team-yubune/loop-pilot";

function resolved(opts: CallerOptions) {
  return {
    language: opts.language ?? "node",
    ref: opts.ref ?? "v1",
    actionRepo: opts.actionRepo ?? DEFAULT_REPO,
    sameRepo: opts.sameRepo ?? false,
  };
}

const S = "${{ secrets."; // keep the literal expression out of template parsing
const E = " }}";

function initSecretsBlock(sameRepo: boolean): string[] {
  if (sameRepo) return ["    secrets: inherit"];
  return [
    "    secrets:",
    `      CODEX_REVIEW_REQUEST_TOKEN: ${S}CODEX_REVIEW_REQUEST_TOKEN${E}`,
  ];
}

function loopSecretsBlock(sameRepo: boolean): string[] {
  if (sameRepo) return ["    secrets: inherit"];
  return [
    "    secrets:",
    `      CODEX_REVIEW_REQUEST_TOKEN: ${S}CODEX_REVIEW_REQUEST_TOKEN${E}`,
    `      LOOPPILOT_PUSH_TOKEN: ${S}LOOPPILOT_PUSH_TOKEN${E}`,
    "      # Set exactly one of ANTHROPIC_API_KEY / CLAUDE_CODE_OAUTH_TOKEN.",
    `      ANTHROPIC_API_KEY: ${S}ANTHROPIC_API_KEY${E}`,
    `      CLAUDE_CODE_OAUTH_TOKEN: ${S}CLAUDE_CODE_OAUTH_TOKEN${E}`,
  ];
}

/** Generate `.github/workflows/looppilot-init.yml` (Workflow A caller). */
export function renderInitCaller(opts: CallerOptions = {}): string {
  const { ref, actionRepo, sameRepo } = resolved(opts);
  return (
    [
      "# .github/workflows/looppilot-init.yml",
      "# Generated by `gh looppilot init`. Thin caller — implementation lives in",
      `# the reusable workflow ${actionRepo}/.github/workflows/init.yml@${ref}.`,
      "name: LoopPilot Init",
      "",
      "on:",
      "  pull_request:",
      "    types: [opened, ready_for_review, labeled]",
      "",
      "jobs:",
      "  init:",
      "    permissions:",
      "      contents: read",
      "      pull-requests: write",
      "      issues: write",
      `    uses: ${actionRepo}/.github/workflows/init.yml@${ref}`,
      ...initSecretsBlock(sameRepo),
    ].join("\n") + "\n"
  );
}

/** Generate `.github/workflows/looppilot-loop.yml` (Workflow B caller). */
export function renderLoopCaller(opts: CallerOptions = {}): string {
  const { language, ref, actionRepo, sameRepo } = resolved(opts);
  return (
    [
      "# .github/workflows/looppilot-loop.yml",
      "# Generated by `gh looppilot init`. Thin caller — implementation lives in",
      `# the reusable workflow ${actionRepo}/.github/workflows/loop.yml@${ref}.`,
      "name: LoopPilot Loop",
      "",
      "on:",
      "  issue_comment:",
      "    types: [created]",
      "  pull_request_review:",
      "    types: [submitted]",
      "",
      "jobs:",
      "  loop:",
      "    permissions:",
      "      contents: write",
      "      pull-requests: write",
      "      issues: write",
      "      actions: read",
      `    uses: ${actionRepo}/.github/workflows/loop.yml@${ref}`,
      ...loopSecretsBlock(sameRepo),
      "    with:",
      `      language: ${language}`,
    ].join("\n") + "\n"
  );
}

export interface GeneratedCaller {
  path: string;
  content: string;
}

/** Both callers with their target paths. */
export function renderCallers(opts: CallerOptions = {}): GeneratedCaller[] {
  return [
    { path: ".github/workflows/looppilot-init.yml", content: renderInitCaller(opts) },
    { path: ".github/workflows/looppilot-loop.yml", content: renderLoopCaller(opts) },
  ];
}
